"""Build flash-resident 400x300 monochrome photos and matching previews."""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import tempfile

from PIL import Image, ImageDraw, ImageEnhance, ImageFont, ImageOps

ROOT = Path(__file__).resolve().parents[1]
SIZE = (400, 300)
FRAME_BYTES = 15000
MAX_PHOTOS = 100
SUPPORTED = {".jpg", ".jpeg", ".png", ".bmp", ".webp"}


def prepare_image(image: Image.Image, fit: str = "contain", contrast: float = 1.0) -> Image.Image:
    image = ImageOps.exif_transpose(image).convert("RGBA")
    background = Image.new("RGBA", image.size, "white")
    background.alpha_composite(image)
    gray = background.convert("L")
    if fit == "cover":
        canvas = ImageOps.fit(gray, SIZE, method=Image.Resampling.LANCZOS)
    elif fit == "contain":
        fitted = ImageOps.contain(gray, SIZE, method=Image.Resampling.LANCZOS)
        canvas = Image.new("L", SIZE, 255)
        canvas.paste(fitted, ((400 - fitted.width) // 2, (300 - fitted.height) // 2))
    else:
        raise ValueError("fit must be contain or cover")
    if contrast <= 0:
        raise ValueError("contrast must be positive")
    return ImageEnhance.Contrast(canvas).enhance(contrast).convert(
        "1", dither=Image.Dither.FLOYDSTEINBERG
    )


def demo_images() -> list[tuple[str, Image.Image]]:
    """Original test cards, not substitutes for the user's photographs."""
    result = []
    font = ImageFont.load_default(size=26)
    small = ImageFont.load_default(size=16)
    for number in range(1, 4):
        im = Image.new("L", SIZE, "white")
        draw = ImageDraw.Draw(im)
        draw.rectangle((10, 10, 389, 289), outline=0, width=2)
        draw.text((25, 24), f"COUPLE FRAME / {number:02d}", font=font, fill=0)
        draw.text((25, 61), "DEMO - replace with your photos", font=small, fill=0)
        if number == 1:
            draw.ellipse((84, 112, 185, 214), fill=0)
            draw.ellipse((205, 112, 306, 214), outline=0, width=5)
            draw.line((135, 164, 256, 164), fill=0, width=3)
        elif number == 2:
            for x in range(32, 368):
                shade = int((x - 32) * 255 / 335)
                draw.line((x, 112, x, 214), fill=shade)
        else:
            for row in range(5):
                for col in range(16):
                    if (row + col) % 2 == 0:
                        draw.rectangle((40 + col*20, 111 + row*20,
                                        59 + col*20, 130 + row*20), fill=0)
        draw.text((25, 253), "Offline  |  next picture: 60 seconds", font=small, fill=0)
        result.append((f"demo-{number:02d}", im))
    return result


def build_album(items: list[tuple[str, Image.Image]], sketch: Path, preview: Path,
                fit: str = "contain", contrast: float = 1.0) -> dict:
    if not 1 <= len(items) <= MAX_PHOTOS:
        raise ValueError(f"Expected 1..{MAX_PHOTOS} photos, got {len(items)}")
    frames = [(name, prepare_image(image, fit, contrast)) for name, image in items]
    raw_frames = [image.tobytes() for _, image in frames]
    if any(len(raw) != FRAME_BYTES for raw in raw_frames):
        raise ValueError("Invalid packed image size")
    # Validate the whole album before replacing any generated sketch files.
    sketch.mkdir(parents=True, exist_ok=True)
    preview.mkdir(parents=True, exist_ok=True)
    header = (
        "// Generated by tools/prepare_photos.py. White=1, black=0, MSB first.\n"
        "#pragma once\n#include <stddef.h>\n#include <stdint.h>\n"
        "constexpr size_t kPhotoBytes = 15000;\n"
        f"constexpr size_t kPhotoCount = {len(frames)};\n"
        "extern const uint8_t kPhotos[kPhotoCount][kPhotoBytes];\n"
    )
    lines = ['#include <Arduino.h>', '#include "Photos.h"',
             'const uint8_t kPhotos[kPhotoCount][kPhotoBytes] PROGMEM = {']
    for raw in raw_frames:
        lines.append('  {')
        for offset in range(0, len(raw), 24):
            lines.append('    ' + ','.join(f'0x{b:02x}' for b in raw[offset:offset+24]) + ',')
        lines.append('  },')
    lines.append('};\n')
    with tempfile.TemporaryDirectory(dir=sketch) as temporary:
        stage = Path(temporary)
        (stage / "Photos.h").write_text(header, encoding="utf-8")
        (stage / "Photos.cpp").write_text('\n'.join(lines), encoding="utf-8")
        for filename in ("Photos.h", "Photos.cpp"):
            (stage / filename).replace(sketch / filename)
    manifest = {"size": list(SIZE), "format": "1-bit, white=1, black=0, MSB first",
                "count": len(frames), "pixel_bytes": len(frames) * FRAME_BYTES,
                "fit": fit, "photos": []}
    for i, ((name, im), raw) in enumerate(zip(frames, raw_frames), 1):
        filename = f"{i:03d}.png"
        im.save(preview / filename)
        manifest["photos"].append({"source": name, "preview": filename,
                                   "sha256": hashlib.sha256(raw).hexdigest()})
    (preview / "manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8")
    return manifest


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", nargs="?", type=Path, default=ROOT / "photos")
    parser.add_argument("--demo", action="store_true")
    parser.add_argument("--fit", choices=("contain", "cover"), default="contain")
    parser.add_argument("--contrast", type=float, default=1.0)
    parser.add_argument("--sketch", type=Path, default=ROOT / "CoupleFrame")
    parser.add_argument("--preview", type=Path, default=ROOT / "preview")
    args = parser.parse_args()
    try:
        if args.demo:
            items = demo_images()
        else:
            if not args.input.is_dir():
                raise ValueError(f"Photo folder does not exist: {args.input}")
            files = sorted((p for p in args.input.iterdir() if p.suffix.lower() in SUPPORTED),
                           key=lambda p: (p.name.casefold(), p.name))
            if not files:
                raise ValueError("No JPG/PNG/BMP/WebP photos found. Export HEIC as JPEG first.")
            if len(files) > MAX_PHOTOS:
                raise ValueError(f"Maximum {MAX_PHOTOS} photos per album")
            items = []
            for path in files:
                with Image.open(path) as image:
                    image.load()
                    items.append((path.name, image.copy()))
        manifest = build_album(items, args.sketch, args.preview, args.fit, args.contrast)
        print(f"Ready: {manifest['count']} photos, {manifest['pixel_bytes']} pixel bytes")
        print(f"Preview: {args.preview.resolve()}")
        print(f"Open: {(args.sketch / 'CoupleFrame.ino').resolve()}")
    except (OSError, ValueError) as exc:
        parser.exit(1, f"Photo preparation failed: {exc}\n")


if __name__ == "__main__":
    main()
